version: "3"

services:
  node1:
    build:
      context: ./chord_node
    container_name: chord_node_1
    environment:
      - NODE_IP=chord_node_1
      - NODE_PORT=5000
      - M_BITS=7
      - DEBUG_MODE=True   # Enable debugging
    ports:
      - "5001:5000"
      - "5678:5678"  # Expose debugger port
    networks:
      chord_network:
        aliases:
          - chord_node_1
    volumes:
      - ./chord_node:/app
    command: ["python3", "-u", "api.py"]

  node2:
    build:
      context: ./chord_node
    container_name: chord_node_2
    environment:
      - NODE_IP=chord_node_2
      - NODE_PORT=5000
      - M_BITS=7
      - DEBUG_MODE=True   # Enable debugging
    ports:
      - "5002:5000"
      - "5679:5678"  # Expose debugger port
    networks:
      chord_network:
        aliases:
          - chord_node_2
    volumes:
      - ./chord_node:/app
    # depends_on:
    #   - node1
    command: ["sh", "-c", "sleep 5 && python3 -u api.py && curl -X POST -d 'chord_node_1:5000' http://localhost:5000/join"]

  node3:
    build:
      context: ./chord_node
    container_name: chord_node_3
    environment:
      - NODE_IP=chord_node_3
      - NODE_PORT=5000
      - M_BITS=7
      - DEBUG_MODE=True   # Enable debugging
    ports:
      - "5003:5000"
      - "5680:5678"  # Expose debugger port
    networks:
      chord_network:
        aliases:
          - chord_node_3
    volumes:
      - ./chord_node:/app
    # depends_on:
    #   - node1
    #   - node2
    command: ["sh", "-c", "sleep 10 && python3 -u api.py && curl -X POST -d 'chord_node_1:5000' http://localhost:5000/join"]
  node4:
    build:
      context: ./chord_node
    container_name: chord_node_4
    environment:
      - NODE_IP=chord_node_4
      - NODE_PORT=5000
      - M_BITS=7
      - DEBUG_MODE=True   # Enable debugging
    ports:
      - "5004:5000"
      - "5681:5678"  # Expose debugger port
    networks:
      chord_network:
        aliases:
          - chord_node_4
    volumes:
      - ./chord_node:/app
    # depends_on:
    #   - node1
    #   - node2
    #   - node3
    command: ["sh", "-c", "sleep 15 && python3 -u api.py && curl -X POST -d 'chord_node_1:5000' http://localhost:5000/join"]

  node5:
    build:
      context: ./chord_node
    container_name: chord_node_5
    environment:
      - NODE_IP=chord_node_5
      - NODE_PORT=5000
      - M_BITS=7
      - DEBUG_MODE=True   # Enable debugging
    ports:
      - "5005:5000"
      - "5682:5678"  # Expose debugger port
    networks:
      chord_network:
        aliases:
          - chord_node_5
    volumes:
      - ./chord_node:/app
    # depends_on:
    #   - node1
    #   - node2
    #   - node3
    command: ["sh", "-c", "sleep 15 && python3 -u api.py && curl -X POST -d 'chord_node_1:5000' http://localhost:5000/join"]
  
  node6:
    build:
      context: ./chord_node
    container_name: chord_node_6
    environment:
      - NODE_IP=chord_node_6
      - NODE_PORT=5000
      - M_BITS=7
      - DEBUG_MODE=True   # Enable debugging
    ports:
      - "5006:5000"
      - "5683:5678"  # Expose debugger port
    networks:
      chord_network:
        aliases:
          - chord_node_6
    volumes:
      - ./chord_node:/app
    # depends_on:
    #   - node1
    #   - node2
    #   - node3
    command: ["sh", "-c", "sleep 15 && python3 -u api.py && curl -X POST -d 'chord_node_1:5000' http://localhost:5000/join"]

  node7:
    build:
      context: ./chord_node
    container_name: chord_node_7
    environment:
      - NODE_IP=chord_node_7
      - NODE_PORT=5000
      - M_BITS=7
      - DEBUG_MODE=True   # Enable debugging
    ports:
      - "5007:5000"
      - "5684:5678"  # Expose debugger port
    networks:
      chord_network:
        aliases:
          - chord_node_7
    volumes:
      - ./chord_node:/app
    # depends_on:
    #   - node1
    #   - node2
    #   - node3
    command: ["sh", "-c", "sleep 15 && python3 -u api.py && curl -X POST -d 'chord_node_1:5000' http://localhost:5000/join"]

  node8:
    build:
      context: ./chord_node
    container_name: chord_node_8
    environment:
      - NODE_IP=chord_node_8
      - NODE_PORT=5000
      - M_BITS=7
      - DEBUG_MODE=True   # Enable debugging
    ports:
      - "5008:5000"
      - "5685:5678"  # Expose debugger port
    networks:
      chord_network:
        aliases:
          - chord_node_8
    volumes:
      - ./chord_node:/app
    # depends_on:
    #   - node1
    #   - node2
    #   - node3
    command: ["sh", "-c", "sleep 15 && python3 -u api.py && curl -X POST -d 'chord_node_1:5000' http://localhost:5000/join"]
networks:
  chord_network:
    driver: bridge