version: "3"

services:
  node1:
    build:
      context: ./chord_node
    container_name: chord_node_1
    environment:
      - NODE_IP=chord_node_1
      - NODE_PORT=5000
      - M_BITS=7
      - DEBUG_MODE=True   # Enable debugging
    ports:
      - "5001:5000"
      - "5678:5678"  # Expose debugger port
    networks:
      chord_network:
        aliases:
          - chord_node_1
    volumes:
      - ./chord_node:/app
    command: ["python", "-u", "api.py"]

  node2:
    build:
      context: ./chord_node
    container_name: chord_node_2
    environment:
      - NODE_IP=chord_node_2
      - NODE_PORT=5000
      - M_BITS=7
      - DEBUG_MODE=True   # Enable debugging
    ports:
      - "5002:5000"
      - "5679:5678"  # Expose debugger port
    networks:
      chord_network:
        aliases:
          - chord_node_2
    volumes:
      - ./chord_node:/app
    depends_on:
      - node1
    command: ["sh", "-c", "sleep 5 && python -u api.py && curl -X POST -d 'chord_node_1:5000' http://localhost:5000/join"]

  node3:
    build:
      context: ./chord_node
    container_name: chord_node_3
    environment:
      - NODE_IP=chord_node_3
      - NODE_PORT=5000
      - M_BITS=7
      - DEBUG_MODE=True   # Enable debugging
    ports:
      - "5003:5000"
      - "5680:5678"  # Expose debugger port
    networks:
      chord_network:
        aliases:
          - chord_node_3
    volumes:
      - ./chord_node:/app
    depends_on:
      - node1
      - node2
    command: ["sh", "-c", "sleep 10 && python -u api.py && curl -X POST -d 'chord_node_1:5000' http://localhost:5000/join"]
  node4:
    build:
      context: ./chord_node
    container_name: chord_node_4
    environment:
      - NODE_IP=chord_node_4
      - NODE_PORT=5000
      - M_BITS=7
      - DEBUG_MODE=True   # Enable debugging
    ports:
      - "5004:5000"
      - "5681:5678"  # Expose debugger port
    networks:
      chord_network:
        aliases:
          - chord_node_4
    volumes:
      - ./chord_node:/app
    depends_on:
      - node1
      - node2
      - node3
    command: ["sh", "-c", "sleep 15 && python -u api.py && curl -X POST -d 'chord_node_1:5000' http://localhost:5000/join"]

networks:
  chord_network:
    driver: bridge